name: vittam-2
region: nyc
services:
  - name: vittam-backend
    github:
      repo: rsp45/Vittam-v2.0.0
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    envs:
      - key: PORT
        value: "8000"
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
        preserve_path_prefix: true
      - path: /v1
        preserve_path_prefix: true
      - path: /health
        preserve_path_prefix: true

  - name: vittam-frontend
    github:
      repo: rsp45/Vittam-v2.0.0
      branch: main
      deploy_on_push: true
    source_dir: frontend_react
    build_command: npm run build
    run_command: npm run start
    envs:
      - key: PORT
        value: "3000"
      - key: HOST
        value: "0.0.0.0"
      - key: VITE_API_URL
        value: ${vittam-backend.PUBLIC_URL}
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
